spring.data.mongodb.database=billing
report.template.path=classpath:templates/invoice_template.jrxml
report.output.path=C:\Users\PC\Desktop\Cours_IDLD_S1\Micro services\LivraisonApp\billing-service\src\main\resources\pdf
